from typing import Protocol


class StorageBackend(Protocol):
    async def upload(self, *, key: str, content: bytes, content_type: str) -> None: ...

    async def download(self, key: str) -> bytes: ...

    async def generate_download_url(self, key: str, expires_in: int = 3600) -> str: ...

    async def delete(self, key: str) -> None: ...
