"""add email_change_requests table

Revision ID: 13862087f70d
Revises: b40fe3e66d6d
Create Date: 2026-08-26 02:49:36.583186

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '13862087f70d'
down_revision: str | None = 'b40fe3e66d6d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_change_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('new_email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_change_requests_token_hash'), 'email_change_requests', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_change_requests_user_id'), 'email_change_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_change_requests_user_id'), table_name='email_change_requests')
    op.drop_index(op.f('ix_email_change_requests_token_hash'), table_name='email_change_requests')
    op.drop_table('email_change_requests')
    # ### end Alembic commands ###
