"""add portfolio_visits table

Revision ID: 16ead3432b1e
Revises: 13862087f70d
Create Date: 2026-08-26 03:05:21.916961

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '16ead3432b1e'
down_revision: str | None = '13862087f70d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_visits',
    sa.Column('chatfolio_id', sa.UUID(), nullable=False),
    sa.Column('visited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chatfolio_id'], ['public_chatfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_visits_chatfolio_id'), 'portfolio_visits', ['chatfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_visits_visited_at'), 'portfolio_visits', ['visited_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_visits_visited_at'), table_name='portfolio_visits')
    op.drop_index(op.f('ix_portfolio_visits_chatfolio_id'), table_name='portfolio_visits')
    op.drop_table('portfolio_visits')
    # ### end Alembic commands ###
