"""create vector_embeddings table

Revision ID: 41ea3eb36748
Revises: 9d522e6ed93c
Create Date: 2026-08-20 07:38:13.233257

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '41ea3eb36748'
down_revision: str | None = '9d522e6ed93c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_embeddings',
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('chroma_ref_id', sa.String(length=255), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chroma_ref_id'),
    sa.UniqueConstraint('source_type', 'source_id', name='uq_vector_embedding_source')
    )
    op.create_index(op.f('ix_vector_embeddings_profile_id'), 'vector_embeddings', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_embeddings_profile_id'), table_name='vector_embeddings')
    op.drop_table('vector_embeddings')
    # ### end Alembic commands ###
