"""create public domains table and add profile plan fields

Revision ID: 5a035f6b6bf2
Revises: 251cd2b9ba23
Create Date: 2026-08-21 15:03:41.827307

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5a035f6b6bf2'
down_revision: str | None = '251cd2b9ba23'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_domains',
    sa.Column('chatfolio_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chatfolio_id'], ['public_chatfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_domains_chatfolio_id'), 'public_domains', ['chatfolio_id'], unique=True)
    op.create_index(op.f('ix_public_domains_domain'), 'public_domains', ['domain'], unique=True)
    # server_default required on both: candidate_profiles already has rows, and these are
    # NOT NULL — without a server-side default, backfilling existing rows fails outright.
    op.add_column('candidate_profiles', sa.Column('plan', sa.String(length=50), nullable=False, server_default='free'))
    op.add_column('candidate_profiles', sa.Column('usage_limits', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'usage_limits')
    op.drop_column('candidate_profiles', 'plan')
    op.drop_index(op.f('ix_public_domains_domain'), table_name='public_domains')
    op.drop_index(op.f('ix_public_domains_chatfolio_id'), table_name='public_domains')
    op.drop_table('public_domains')
    # ### end Alembic commands ###
