"""create public_chatfolios table

Revision ID: 8ef99f864695
Revises: 41ea3eb36748
Create Date: 2026-08-20 10:17:12.654262

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '8ef99f864695'
down_revision: str | None = '41ea3eb36748'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_chatfolios',
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('previous_slug', sa.String(length=63), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_cta_config', sa.JSON(), nullable=False),
    sa.Column('cv_downloadable', sa.Boolean(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', name='uq_public_chatfolio_profile')
    )
    op.create_index(op.f('ix_public_chatfolios_previous_slug'), 'public_chatfolios', ['previous_slug'], unique=False)
    op.create_index(op.f('ix_public_chatfolios_profile_id'), 'public_chatfolios', ['profile_id'], unique=False)
    op.create_index(op.f('ix_public_chatfolios_slug'), 'public_chatfolios', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_chatfolios_slug'), table_name='public_chatfolios')
    op.drop_index(op.f('ix_public_chatfolios_profile_id'), table_name='public_chatfolios')
    op.drop_index(op.f('ix_public_chatfolios_previous_slug'), table_name='public_chatfolios')
    op.drop_table('public_chatfolios')
    # ### end Alembic commands ###
