"""create portfolio_sections table

Revision ID: 9d522e6ed93c
Revises: 60adad69c93e
Create Date: 2026-08-20 06:09:21.481101

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '9d522e6ed93c'
down_revision: str | None = '60adad69c93e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_sections',
    sa.Column('section_type', sa.Enum('INTRO', 'SUMMARY', name='section_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', name='section_status'), nullable=False),
    sa.Column('generated_by', sa.Enum('AI', 'MANUAL', name='generated_by'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'section_type', name='uq_portfolio_section_profile_type')
    )
    op.create_index(op.f('ix_portfolio_sections_profile_id'), 'portfolio_sections', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_sections_profile_id'), table_name='portfolio_sections')
    op.drop_table('portfolio_sections')
    # ### end Alembic commands ###
