"""add two factor, password reset, otp support

Revision ID: 9ed9941a563a
Revises: 5a035f6b6bf2
Create Date: 2026-08-23 00:30:11.678016

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '9ed9941a563a'
down_revision: str | None = '5a035f6b6bf2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('TWO_FACTOR_ENROLL', 'TWO_FACTOR_LOGIN', name='otp_purpose'), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'PHONE', 'BOTH', name='otp_channel'), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_user_id'), 'otp_codes', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.add_column('users', sa.Column('phone', sa.String(length=32), nullable=True))
    # server_default required: users already has rows, and this is NOT NULL.
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ALTER TABLE ADD COLUMN doesn't auto-create the enum type the way CREATE TABLE does — create
    # it explicitly first (same values as otp_channel, just a separately-named Postgres type).
    two_factor_method_enum = sa.Enum('EMAIL', 'PHONE', 'BOTH', name='two_factor_method')
    two_factor_method_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('two_factor_method', two_factor_method_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_method')
    sa.Enum(name='two_factor_method').drop(op.get_bind(), checkfirst=True)
    op.drop_column('users', 'two_factor_enabled')
    op.drop_column('users', 'phone')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_otp_codes_user_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
