"""add ai_tokens_used to candidate_profiles

Revision ID: b40fe3e66d6d
Revises: 9ed9941a563a
Create Date: 2026-08-26 02:24:50.439952

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b40fe3e66d6d'
down_revision: str | None = '9ed9941a563a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default required: candidate_profiles already has rows, and this is NOT NULL.
    op.add_column(
        'candidate_profiles',
        sa.Column('ai_tokens_used', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'ai_tokens_used')
    # ### end Alembic commands ###
